"""Add status column to friendships

Revision ID: 09f1370afdac
Revises: 34c0226838ca
Create Date: 2024-12-16 16:06:39.631616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f1370afdac'
down_revision: Union[str, None] = '34c0226838ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='friendshipstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'status')
    # ### end Alembic commands ###
