"""use supabase auth

Revision ID: 34c0226838ca
Revises: 60abb5d6418a
Create Date: 2024-12-15 16:05:08.145383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c0226838ca'
down_revision: Union[str, None] = '60abb5d6418a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'clerk_id')
    op.add_column('users', sa.Column('supabase_id', sa.String(), nullable=True))
    op.drop_index('ix_users_clerk_id', table_name='users')
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.create_index('ix_users_clerk_id', 'users', ['clerk_id'], unique=True)
    op.drop_column('users', 'supabase_id')
    op.add_column('sessions', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
