"""Add user_profile_created column to users

Revision ID: 692108cf4637
Revises: 5276904d5a70
Create Date: 2024-12-12 19:56:23.368133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692108cf4637'
down_revision: Union[str, None] = '5276904d5a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_profile_created', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_profile_created')
    # ### end Alembic commands ###
