"""Add new_column to my_table

Revision ID: d163892b1cc5
Revises: 692108cf4637
Create Date: 2024-12-13 17:43:34.779354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd163892b1cc5'
down_revision: Union[str, None] = '692108cf4637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('clerk_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['clerk_id'], ['clerk_id'])
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'clerk_id')
    # ### end Alembic commands ###
