"""Updated friendships table

Revision ID: ed118dda3e1c
Revises: d163892b1cc5
Create Date: 2024-12-13 19:31:16.354110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed118dda3e1c'
down_revision: Union[str, None] = 'd163892b1cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'status')
    op.drop_column('friendships', 'updated_at')
    op.drop_constraint('sessions_clerk_id_fkey', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'clerk_id')
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('sessions', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('sessions_clerk_id_fkey', 'sessions', 'users', ['clerk_id'], ['clerk_id'])
    op.add_column('friendships', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('friendships', sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='friendshipstatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
